### ISSUE TITLE
error in kaiju.report

### ISSUE THREAD

**Issue by Jerry-kiwi** [bioinformatics-centre/kaiju#52] opened 2017-11-05 05:37 UTC
./kaijuReport -t kaiju_db/kaiju_index/nodes.dmp -n kaiju_db/kaiju_index/names.dmp -i RefSeq_13_S28.kaiju.out.csv -r species -o RefSeq_13_S28.kaiju.out.summary

I'm getting there lines for viruses:

`
    %	    reads	species
-------------------------------------------
 3.420722	     1661	Alistipes finegoldii
 0.988529	      480	Bacteroides cellulosilyticus
 0.683733	      332	Bacteroides fragilis
 0.595177	      289	Bacteroides thetaiotaomicron
 0.570464	      277	Bacteroides ovatus
 0.313034	      152	Bacteroides caecimuris
-------------------------------------------
66.775131	    32424	Viruses
 3.562823	     1730	cannot be assigned to a species 
-------------------------------------------
21.152461	    10271	unclassified
`
It seems, that kaiju can't split viruses to speies in report file, but able to do in in krona file.

**Comment by pmenzel** [comment] 2017-11-06 10:10
Hi,

it is intended behavior: kaijuReport puts all reads assigned to viruses in the same generic bin.
There were some issues some time ago that gave weird output for viruses when selecting `-r genus` or `-r family`, so I changed it to the current behaviour.

If you need full taxon paths for viruses, then please use the output of `kaiju2krona`.

**Closed** 2017-11-28 10:05 UTC
